#!/usr/bin/env python3
import json, time, serial

# Path to stats file (adjust to your setup)
STATS_FILE = "/run/readsb/stats.json"
SERIAL_PORT = "/dev/ttyAML0"  # check your UART device (use `dmesg | grep tty`)
BAUDRATE = 9600


def get_stats():
    try:
        with open(STATS_FILE) as f:
            data = json.load(f)
        print("File open")

        messageCount = data["last1min"]["messages_valid"] if "last1min" in data else 0
        messageRate = round(messageCount / 60)
        print("messageRate:",messageRate)

        posCount=data["last1min"]["position_count_total"] if "last1min" in data else 0
        print("posCount:",posCount)

        aircraftCount = data["aircraft_with_pos"] if "aircraft_with_pos" in data else 0
        print("aircraftCount:",aircraftCount)

        greater_3dbfs = data["last1min"]["local"]["strong_signals"] if "last1min" in data else 0
        print(">3dfs:",greater_3dbfs)

        sdbr = round((greater_3dbfs / messageCount)*100,2)
        print("Strong Signal Ratio",sdbr,"%")

        return messageRate, aircraftCount,  posCount, greater_3dbfs, sdbr
    except Exception as e:
        print("Exception")
        return 0, 0, 0, 0, 0


def main():
    ser = serial.Serial(SERIAL_PORT, BAUDRATE, timeout=1)
    while True:
        msg_rate, acCount, posCount,  strong, strongRatio = get_stats()
        line = f"msgRate:{msg_rate},posCount:{posCount},acCount:{acCount},3DB:{strong},3DBR:{strongRatio}\n"
        ser.write(line.encode("utf-8"))
        time.sleep(5)


if __name__ == "__main__":
    main()
